Fix/analytics
youroffer/require-service pull request #20
Opened 2024-12-11 21:21 UTC by ViktorMurman12

2024-12-11 23:35 UTC, himmel520 requested changes

2024-12-11 23:35 UTC, himmel520 commented on internal/infrastructure/repository/analytic_params.go
параметры для какой ручки?

2024-12-11 23:35 UTC, himmel520 commented on internal/infrastructure/repository/postgres/analytic/create.go
> +	var vacanciesNum sql.NullInt64
var (
    тут переменные  с типами
)

2024-12-11 23:35 UTC, himmel520 commented on internal/infrastructure/repository/postgres/analytic/get.go
> +		analytic := &entity.AnalyticResp{}
ну вот опять, ты или все в вар или через :=

2024-12-11 23:35 UTC, himmel520 commented on internal/infrastructure/repository/postgres/analytic/update.go
> +	var vacanciesNum sql.NullInt64
снова

2024-12-11 23:35 UTC, himmel520 commented on internal/usecase/analitic_page_params.go
название файла((

2024-12-11 23:35 UTC, himmel520 commented on internal/usecase/analitic_page_params.go
и параметры страницы везде для всех одинаковые, тем более у тебя есть pageparams, что мешает наследовать

2024-12-12 11:15 UTC, ViktorMurman12 commented on internal/infrastructure/repository/analytic_params.go
deleted

2024-12-12 11:26 UTC, ViktorMurman12 commented on internal/usecase/analitic_page_params.go
Файл не используется, был удален

2024-12-12 15:31 UTC, himmel520 approved these changes

2024-12-12 15:31 UTC, merged